choco install opera-gx -y
choco install flow-launcher -y
choco install tabby -y
choco install bitwarden -y
choco install powertoys -y
choco install pwsh -y
choco install discord.install -y
choco install git.install -y
choco install eartrumpet -y
choco install sublimetext4 -y
choco install path-copy-copy -y